import type {
  User,
  Batch,
  Task,
  Session,
  Review,
  Notification,
  DashboardStats,
  AnalyticsData,
} from "./types"

// ============================================
// TEST USERS FOR DIFFERENT ROLES
// ============================================
// To test different roles, change currentUser to one of these:
// - testAnnotator (annotator role)
// - testReviewer (reviewer role)  
// - testAdmin (admin role)
// ============================================

export const testAnnotator: User = {
  id: "usr_001",
  name: "Alex Chen",
  email: "alex.chen@labelforge.ai",
  role: "annotator",
  department: "AI Training",
  joinedAt: "2024-01-15",
}

export const testReviewer: User = {
  id: "usr_002",
  name: "Sarah Johnson",
  email: "sarah.j@labelforge.ai",
  role: "reviewer",
  department: "Quality Assurance",
  joinedAt: "2023-11-20",
}

export const testAdmin: User = {
  id: "usr_003",
  name: "Michael Park",
  email: "m.park@labelforge.ai",
  role: "admin",
  department: "Operations",
  joinedAt: "2023-06-10",
}

// CHANGE THIS TO TEST DIFFERENT ROLES
// Options: testAnnotator, testReviewer, testAdmin
export const currentUser: User = testAnnotator

export const users: User[] = [
  testAnnotator,
  testReviewer,
  testAdmin,
  {
    id: "usr_004",
    name: "Emily Davis",
    email: "e.davis@labelforge.ai",
    role: "annotator",
    department: "AI Training",
    joinedAt: "2024-02-01",
  },
  {
    id: "usr_005",
    name: "James Wilson",
    email: "j.wilson@labelforge.ai",
    role: "annotator",
    department: "AI Training",
    joinedAt: "2024-03-15",
  },
  {
    id: "usr_006",
    name: "Maria Garcia",
    email: "m.garcia@labelforge.ai",
    role: "reviewer",
    department: "Quality Assurance",
    joinedAt: "2024-01-10",
  },
]

// Priority uses decimal 0-1, displayed as P0-P4
// P0 = 0.9-1.0 (highest/urgent)
// P1 = 0.7-0.89 (high)
// P2 = 0.5-0.69 (medium)
// P3 = 0.3-0.49 (low)
// P4 = 0-0.29 (lowest)

export const batches: Batch[] = [
  {
    id: "batch_001",
    title: "Agent Task Completion - Web Navigation",
    description: "Complete complex multi-step tasks on external websites to train agentic AI behaviors",
    taskType: "agentic-ai",
    priority: 0.95, // P0
    deadline: "2026-04-25",
    workloadEstimate: 40,
    status: "available",
    tasksTotal: 50,
    tasksCompleted: 0,
    createdAt: "2026-04-10",
  },
  {
    id: "batch_002",
    title: "Customer Support Response Training",
    description: "Generate and evaluate customer support responses for various scenarios",
    taskType: "llm-training",
    priority: 0.55, // P2
    deadline: "2026-04-30",
    workloadEstimate: 25,
    status: "in-progress",
    tasksTotal: 100,
    tasksCompleted: 45,
    createdAt: "2026-04-08",
    assignedTo: ["usr_001", "usr_004"],
  },
  {
    id: "batch_003",
    title: "Image-Text Alignment Evaluation",
    description: "Evaluate the alignment between generated images and their text descriptions",
    taskType: "multimodal",
    priority: 0.5, // P2
    deadline: "2026-05-05",
    workloadEstimate: 30,
    status: "available",
    tasksTotal: 75,
    tasksCompleted: 0,
    createdAt: "2026-04-12",
  },
  {
    id: "batch_004",
    title: "Model Safety Red Teaming",
    description: "Attempt to find vulnerabilities and safety issues in the latest model version",
    taskType: "red-teaming",
    priority: 1.0, // P0
    deadline: "2026-04-22",
    workloadEstimate: 20,
    status: "in-progress",
    tasksTotal: 30,
    tasksCompleted: 18,
    createdAt: "2026-04-05",
    assignedTo: ["usr_001"],
  },
  {
    id: "batch_005",
    title: "Response Quality Benchmarking",
    description: "Compare model responses against baseline benchmarks across multiple categories",
    taskType: "benchmarking",
    priority: 0.25, // P4
    deadline: "2026-05-15",
    workloadEstimate: 35,
    status: "available",
    tasksTotal: 60,
    tasksCompleted: 0,
    createdAt: "2026-04-14",
  },
  {
    id: "batch_006",
    title: "Preference Ranking Study",
    description: "Rank model responses based on helpfulness, accuracy, and safety",
    taskType: "preference-ranking",
    priority: 0.75, // P1
    deadline: "2026-04-28",
    workloadEstimate: 15,
    status: "completed",
    tasksTotal: 40,
    tasksCompleted: 40,
    createdAt: "2026-04-01",
    assignedTo: ["usr_001", "usr_004", "usr_005"],
  },
  {
    id: "batch_007",
    title: "Code Generation Evaluation",
    description: "Evaluate quality and correctness of generated code across multiple languages",
    taskType: "evaluation",
    priority: 0.8, // P1
    deadline: "2026-04-27",
    workloadEstimate: 30,
    status: "available",
    tasksTotal: 45,
    tasksCompleted: 0,
    createdAt: "2026-04-15",
  },
]

// Tasks - each user can only have ONE in-progress task at a time
export const tasks: Task[] = [
  // ANNOTATOR (usr_001) tasks - note: only ONE is in-progress
  {
    id: "task_001",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    title: "Handle refund request scenario",
    description: "Generate appropriate responses for a customer requesting a refund for a damaged product received last week",
    taskType: "llm-training",
    status: "in-progress", // This is the ONLY in-progress task for usr_001
    priority: 0.55,
    estimatedDuration: 15,
    actualDuration: 10,
    startedAt: "2026-04-19T09:30:00Z",
    assignedTo: "usr_001",
  },
  {
    id: "task_002",
    batchId: "batch_004",
    batchTitle: "Model Safety Red Teaming",
    title: "Test prompt injection resistance",
    description: "Attempt various prompt injection techniques and document model responses and any vulnerabilities found",
    taskType: "red-teaming",
    status: "submitted",
    priority: 1.0,
    externalUrl: "https://redteam.internal.ai/session/abc123",
    estimatedDuration: 30,
    actualDuration: 28,
    startedAt: "2026-04-18T14:00:00Z",
    completedAt: "2026-04-18T14:28:00Z",
    submittedAt: "2026-04-18T14:30:00Z",
    assignedTo: "usr_001",
  },
  {
    id: "task_003",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    title: "Technical troubleshooting guidance",
    description: "Provide step-by-step troubleshooting for common technical issues with software installation",
    taskType: "llm-training",
    status: "approved",
    priority: 0.55,
    estimatedDuration: 20,
    actualDuration: 18,
    startedAt: "2026-04-17T10:00:00Z",
    completedAt: "2026-04-17T10:18:00Z",
    submittedAt: "2026-04-17T10:20:00Z",
    assignedTo: "usr_001",
    reviewedBy: "usr_002",
    qualityScore: 92,
    feedback: "Excellent responses with clear step-by-step instructions. Good use of numbered lists.",
  },
  {
    id: "task_004",
    batchId: "batch_001",
    batchTitle: "Agent Task Completion - Web Navigation",
    title: "Book a flight reservation",
    description: "Navigate to a travel website and complete a flight booking process from search to confirmation",
    taskType: "agentic-ai",
    status: "not-started",
    priority: 0.95,
    externalUrl: "https://demo-travel.com/flights",
    estimatedDuration: 25,
    assignedTo: "usr_001",
  },
  {
    id: "task_005",
    batchId: "batch_004",
    batchTitle: "Model Safety Red Teaming",
    title: "Test content policy boundaries",
    description: "Evaluate model responses at the edge of content policies and document any inconsistencies",
    taskType: "red-teaming",
    status: "revision-requested",
    priority: 1.0,
    estimatedDuration: 25,
    actualDuration: 22,
    startedAt: "2026-04-16T11:00:00Z",
    completedAt: "2026-04-16T11:22:00Z",
    submittedAt: "2026-04-16T11:25:00Z",
    assignedTo: "usr_001",
    reviewedBy: "usr_002",
    feedback: "Please add more detailed documentation of the edge cases tested. Include specific prompts used.",
  },
  {
    id: "task_006",
    batchId: "batch_006",
    batchTitle: "Preference Ranking Study",
    title: "Rank coding assistance responses",
    description: "Compare and rank 5 model responses for a coding help request about sorting algorithms",
    taskType: "preference-ranking",
    status: "approved",
    priority: 0.75,
    estimatedDuration: 10,
    actualDuration: 8,
    startedAt: "2026-04-15T09:00:00Z",
    completedAt: "2026-04-15T09:08:00Z",
    submittedAt: "2026-04-15T09:10:00Z",
    assignedTo: "usr_001",
    reviewedBy: "usr_002",
    qualityScore: 95,
    feedback: "Well-reasoned rankings with clear justifications for each position.",
  },
  {
    id: "task_007",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    title: "Handle billing dispute",
    description: "Generate responses for a customer disputing charges on their account for the past month",
    taskType: "llm-training",
    status: "not-started",
    priority: 0.55,
    estimatedDuration: 15,
    assignedTo: "usr_001",
  },
  {
    id: "task_008",
    batchId: "batch_001",
    batchTitle: "Agent Task Completion - Web Navigation",
    title: "Fill out insurance form",
    description: "Complete a multi-page insurance application form with provided test data",
    taskType: "agentic-ai",
    status: "not-started",
    priority: 0.95,
    externalUrl: "https://demo-insurance.com/apply",
    estimatedDuration: 30,
    assignedTo: "usr_001",
  },
  // ANNOTATOR (usr_004) tasks
  {
    id: "task_009",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    title: "Product return process",
    description: "Guide customer through the product return and exchange process",
    taskType: "llm-training",
    status: "in-progress", // Only in-progress task for usr_004
    priority: 0.55,
    estimatedDuration: 12,
    startedAt: "2026-04-19T10:00:00Z",
    assignedTo: "usr_004",
  },
  {
    id: "task_010",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    title: "Account recovery assistance",
    description: "Help customer recover access to their locked account",
    taskType: "llm-training",
    status: "submitted",
    priority: 0.55,
    estimatedDuration: 10,
    actualDuration: 9,
    startedAt: "2026-04-19T08:00:00Z",
    completedAt: "2026-04-19T08:09:00Z",
    submittedAt: "2026-04-19T08:10:00Z",
    assignedTo: "usr_004",
  },
  // ANNOTATOR (usr_005) tasks
  {
    id: "task_011",
    batchId: "batch_006",
    batchTitle: "Preference Ranking Study",
    title: "Rank creative writing samples",
    description: "Rank 5 creative writing outputs based on creativity, coherence, and engagement",
    taskType: "preference-ranking",
    status: "in-progress", // Only in-progress task for usr_005
    priority: 0.75,
    estimatedDuration: 15,
    startedAt: "2026-04-19T09:15:00Z",
    assignedTo: "usr_005",
  },
  {
    id: "task_012",
    batchId: "batch_006",
    batchTitle: "Preference Ranking Study",
    title: "Rank summary quality",
    description: "Rank model-generated summaries of a news article by accuracy and conciseness",
    taskType: "preference-ranking",
    status: "approved",
    priority: 0.75,
    estimatedDuration: 10,
    actualDuration: 11,
    startedAt: "2026-04-18T14:00:00Z",
    completedAt: "2026-04-18T14:11:00Z",
    submittedAt: "2026-04-18T14:12:00Z",
    assignedTo: "usr_005",
    reviewedBy: "usr_006",
    qualityScore: 88,
    feedback: "Good work. Consider providing more detail on ranking criteria in future tasks.",
  },
  // Tasks pending review (for reviewer role testing)
  {
    id: "task_013",
    batchId: "batch_003",
    batchTitle: "Image-Text Alignment Evaluation",
    title: "Evaluate landscape descriptions",
    description: "Assess how well image descriptions match generated landscape images",
    taskType: "multimodal",
    status: "submitted",
    priority: 0.5,
    estimatedDuration: 20,
    actualDuration: 18,
    startedAt: "2026-04-18T11:00:00Z",
    completedAt: "2026-04-18T11:18:00Z",
    submittedAt: "2026-04-18T11:20:00Z",
    assignedTo: "usr_004",
  },
  {
    id: "task_014",
    batchId: "batch_007",
    batchTitle: "Code Generation Evaluation",
    title: "Evaluate Python sorting function",
    description: "Review and score a generated Python implementation of quicksort algorithm",
    taskType: "evaluation",
    status: "submitted",
    priority: 0.8,
    estimatedDuration: 15,
    actualDuration: 14,
    startedAt: "2026-04-18T15:00:00Z",
    completedAt: "2026-04-18T15:14:00Z",
    submittedAt: "2026-04-18T15:15:00Z",
    assignedTo: "usr_005",
  },
]

export const sessions: Session[] = [
  {
    id: "sess_001",
    taskId: "task_001",
    taskTitle: "Handle refund request scenario",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    startTime: "2026-04-19T09:30:00Z",
    duration: 600,
    status: "active",
    eventsRecorded: 45,
  },
  {
    id: "sess_002",
    taskId: "task_002",
    taskTitle: "Test prompt injection resistance",
    batchId: "batch_004",
    batchTitle: "Model Safety Red Teaming",
    startTime: "2026-04-18T14:00:00Z",
    endTime: "2026-04-18T14:28:00Z",
    duration: 1680,
    status: "completed",
    eventsRecorded: 127,
  },
  {
    id: "sess_003",
    taskId: "task_003",
    taskTitle: "Technical troubleshooting guidance",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    startTime: "2026-04-17T10:00:00Z",
    endTime: "2026-04-17T10:18:00Z",
    duration: 1080,
    status: "completed",
    eventsRecorded: 89,
  },
  {
    id: "sess_004",
    taskId: "task_009",
    taskTitle: "Product return process",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    startTime: "2026-04-19T10:00:00Z",
    duration: 420,
    status: "active",
    eventsRecorded: 32,
  },
]

export const reviews: Review[] = [
  {
    id: "rev_001",
    taskId: "task_002",
    taskTitle: "Test prompt injection resistance",
    batchId: "batch_004",
    batchTitle: "Model Safety Red Teaming",
    annotatorId: "usr_001",
    annotatorName: "Alex Chen",
    status: "pending",
    submittedAt: "2026-04-18T14:30:00Z",
  },
  {
    id: "rev_002",
    taskId: "task_003",
    taskTitle: "Technical troubleshooting guidance",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    annotatorId: "usr_001",
    annotatorName: "Alex Chen",
    reviewerId: "usr_002",
    reviewerName: "Sarah Johnson",
    status: "approved",
    submittedAt: "2026-04-17T10:20:00Z",
    reviewedAt: "2026-04-17T11:00:00Z",
    qualityScore: 92,
    feedback: "Excellent responses with clear step-by-step instructions. Good use of numbered lists.",
    criteriaScores: {
      accuracy: 95,
      completeness: 90,
      adherence: 91,
    },
  },
  {
    id: "rev_003",
    taskId: "task_005",
    taskTitle: "Test content policy boundaries",
    batchId: "batch_004",
    batchTitle: "Model Safety Red Teaming",
    annotatorId: "usr_001",
    annotatorName: "Alex Chen",
    reviewerId: "usr_002",
    reviewerName: "Sarah Johnson",
    status: "revision-requested",
    submittedAt: "2026-04-16T11:25:00Z",
    reviewedAt: "2026-04-16T14:00:00Z",
    feedback: "Please add more detailed documentation of the edge cases tested. Include specific prompts used.",
    criteriaScores: {
      accuracy: 85,
      completeness: 70,
      adherence: 88,
    },
  },
  {
    id: "rev_004",
    taskId: "task_006",
    taskTitle: "Rank coding assistance responses",
    batchId: "batch_006",
    batchTitle: "Preference Ranking Study",
    annotatorId: "usr_001",
    annotatorName: "Alex Chen",
    reviewerId: "usr_002",
    reviewerName: "Sarah Johnson",
    status: "approved",
    submittedAt: "2026-04-15T09:10:00Z",
    reviewedAt: "2026-04-15T10:30:00Z",
    qualityScore: 95,
    feedback: "Well-reasoned rankings with clear justifications for each position.",
    criteriaScores: {
      accuracy: 96,
      completeness: 94,
      adherence: 95,
    },
  },
  {
    id: "rev_005",
    taskId: "task_010",
    taskTitle: "Account recovery assistance",
    batchId: "batch_002",
    batchTitle: "Customer Support Response Training",
    annotatorId: "usr_004",
    annotatorName: "Emily Davis",
    status: "pending",
    submittedAt: "2026-04-19T08:10:00Z",
  },
  {
    id: "rev_006",
    taskId: "task_012",
    taskTitle: "Rank summary quality",
    batchId: "batch_006",
    batchTitle: "Preference Ranking Study",
    annotatorId: "usr_005",
    annotatorName: "James Wilson",
    reviewerId: "usr_006",
    reviewerName: "Maria Garcia",
    status: "approved",
    submittedAt: "2026-04-18T14:12:00Z",
    reviewedAt: "2026-04-18T15:00:00Z",
    qualityScore: 88,
    feedback: "Good work. Consider providing more detail on ranking criteria in future tasks.",
    criteriaScores: {
      accuracy: 90,
      completeness: 85,
      adherence: 89,
    },
  },
  {
    id: "rev_007",
    taskId: "task_013",
    taskTitle: "Evaluate landscape descriptions",
    batchId: "batch_003",
    batchTitle: "Image-Text Alignment Evaluation",
    annotatorId: "usr_004",
    annotatorName: "Emily Davis",
    status: "pending",
    submittedAt: "2026-04-18T11:20:00Z",
  },
  {
    id: "rev_008",
    taskId: "task_014",
    taskTitle: "Evaluate Python sorting function",
    batchId: "batch_007",
    batchTitle: "Code Generation Evaluation",
    annotatorId: "usr_005",
    annotatorName: "James Wilson",
    status: "pending",
    submittedAt: "2026-04-18T15:15:00Z",
  },
]

export const notifications: Notification[] = [
  {
    id: "notif_001",
    type: "batch-assigned",
    title: "New Batch Assigned",
    message: "You have been assigned to 'Agent Task Completion - Web Navigation' batch",
    read: false,
    createdAt: "2026-04-19T08:00:00Z",
    actionUrl: "/batches/batch_001",
  },
  {
    id: "notif_002",
    type: "task-approved",
    title: "Task Approved",
    message: "Your task 'Technical troubleshooting guidance' has been approved with a score of 92",
    read: false,
    createdAt: "2026-04-17T11:00:00Z",
    actionUrl: "/tasks/task_003",
  },
  {
    id: "notif_003",
    type: "deadline-warning",
    title: "Deadline Approaching",
    message: "Model Safety Red Teaming batch deadline is in 3 days",
    read: true,
    createdAt: "2026-04-19T06:00:00Z",
    actionUrl: "/batches/batch_004",
  },
  {
    id: "notif_004",
    type: "review-needed",
    title: "Revision Requested",
    message: "Please revise 'Test content policy boundaries' based on reviewer feedback",
    read: false,
    createdAt: "2026-04-16T14:00:00Z",
    actionUrl: "/tasks/task_005",
  },
]

export const dashboardStats: DashboardStats = {
  availableBatches: 4,
  activeTasks: 1,
  completedSessions: 15,
  signedOffTasks: 12,
  pendingReviews: 4,
  averageQualityScore: 91.5,
}

export const analyticsData: AnalyticsData = {
  tasksCompletedByDay: [
    { date: "2026-04-13", count: 5 },
    { date: "2026-04-14", count: 8 },
    { date: "2026-04-15", count: 6 },
    { date: "2026-04-16", count: 10 },
    { date: "2026-04-17", count: 7 },
    { date: "2026-04-18", count: 9 },
    { date: "2026-04-19", count: 4 },
  ],
  tasksByType: [
    { type: "agentic-ai", count: 15 },
    { type: "llm-training", count: 45 },
    { type: "multimodal", count: 12 },
    { type: "evaluation", count: 8 },
    { type: "red-teaming", count: 18 },
    { type: "preference-ranking", count: 25 },
  ],
  qualityScoresTrend: [
    { date: "2026-04-13", score: 88 },
    { date: "2026-04-14", score: 90 },
    { date: "2026-04-15", score: 89 },
    { date: "2026-04-16", score: 92 },
    { date: "2026-04-17", score: 91 },
    { date: "2026-04-18", score: 93 },
    { date: "2026-04-19", score: 92 },
  ],
  annotatorPerformance: [
    { id: "usr_001", name: "Alex Chen", tasksCompleted: 45, averageQuality: 91.5, averageTime: 18 },
    { id: "usr_004", name: "Emily Davis", tasksCompleted: 38, averageQuality: 89.2, averageTime: 22 },
    { id: "usr_005", name: "James Wilson", tasksCompleted: 32, averageQuality: 93.1, averageTime: 20 },
  ],
}
